2018-08-13_10:52:17

diff --git a/bash_sources/mounting b/bash_sources/mounting
--- a/bash_sources/mounting
+++ b/bash_sources/mounting
@@ -6,37 +6,47 @@ fuse-umnt()
     command fusermount -u $@
 }
 
-# DEVICES
-mnt()
-{
-    if [ $1 = "-c" -o $1 = "--custom-name" ]
-    then
-        shift 1
-        $HOME/.bash_sources/scripts/mnt_base $2 $1
-    elif [ $1 = "-p" -o $1 = "--custom-path" ]
-    then
-        shift 1
-        if [ "$(command udisksctl mount -b $2 | true ; echo ${PIPESTATUS[0]})" = "0" ]
-        then
-            MOUNT_LOCATION="$(command udisksctl info -b $2 | command grep MountPoints | command cut -c25-)"
-            echo "$2 linked to $1"
-            echo "    Mounted at "${MOUNT_LOCATION}""
-            command ln -rs "${MOUNT_LOCATION}" $1
+cdm() {
+    if [[ $1 == "-d" ]]; then
+        if [ -d /mnt/drive$2 ]; then
+            cd /mnt/drive$2
+        else
+            cd /mnt/
+        fi
+    elif [[ $1 == "-i" ]]; then
+        if [ -d /mnt/ios$2 ]; then
+            cd /mnt/ios$2
+        else
+            cd /mnt/
         fi
     else
-        x=0
+        cd /mnt/
+    fi
+}
+
+alias lm='ls /mnt/'
+
+
+#-------------------------------------------------------------------------------
+# DEVICES - except iOS
+#-------------------------------------------------------------------------------
+
+mnt()
+{
+    if [ $1 = "-c" -o $1 = "--custom-name" ]; then
+        shift 1
+        $HOME/.bash_sources/scripts/mnt_base $2 $1
+    else
+        i=0
         for x1 in $@
         do
-            flag=true
-            x2="drive0"
-            while [ $flag = true ]
+            while [ true ]
             do
-                if [ -d /mnt/$x2 ]
-                then
-                    (( x++ ))
-                    x2="${x2::5}$x"
+                x2="drive$i"
+                if [ -d /mnt/$x2 ]; then
+                    (( i++ ))
                 else
-                    flag=false
+                    break
                 fi
             done
             $HOME/.bash_sources/scripts/mnt_base $x1 $x2
@@ -47,11 +57,9 @@ mnt()
 umnt()
 {
     cd
-    if [ -e $1 ]
-    then
+    if [ -e $1 ]; then
         command udisksctl unmount -b $1
-    elif [ $1 = "-n" -o $1 = "--numbers" ]
-    then
+    elif [ $1 = "-n" ]; then
         shift 1
         for x in $@
         do
@@ -61,8 +69,7 @@ umnt()
     else
         for x in $@
         do
-            if [ ${x::5} = "drive" ]
-            then
+            if [ ${x::5} = "drive" ]; then
                 $HOME/.bash_sources/scripts/umnt_base $x
             else
                 echo "No such drive"
@@ -71,49 +78,107 @@ umnt()
     fi
 
     LINKS="$(command find /mnt/ -xtype l)"
-    if [ ! "$LINKS" = "" ]
-    then
+
+    if [ ! "$LINKS" = "" ]; then
         unlink $LINKS
         rm /mnt/.${LINKS:5}
     fi
+
     cd - &> /dev/null
 }
 
-cdm() {
-    if [ -d /mnt/drive$1 ]
-    then
-        cd /mnt/drive$1
+
+#-------------------------------------------------------------------------------
+# iOS DEVICES
+#-------------------------------------------------------------------------------
+
+ios-mnt()
+{
+    plugged=$(ideviceinstaller -l 2> /dev/null)
+    if [[ $plugged == "" ]]; then
+        echo "No iOS device found, is it plugged in?"
     else
-        cd /mnt/
+        echo
+        echo -e "\e[4m0 | iOS\e[0m"
+        echo
+
+        i=1
+        while read app
+        do
+            echo $i \| $( echo $app | cut -d "," -f 3 | tr -d '"')
+            appid[$i]=$( echo $app | cut -d "," -f 1 )
+            (( i++ ))
+        done < <(ideviceinstaller -l | sed 1d)
+
+        echo
+        echo "* Type anthing else to abort *"
+        echo
+
+        read -r -p 'Choose index of app: ' option
+
+        j=0
+        while [ true ]
+        do
+            x="ios$j"
+            if [ -d /mnt/$x ]; then
+                (( j++ ))
+            else
+                break
+            fi
+        done
+
+        re='^[0-9]+$'
+        if [[ $option == '0' ]]; then
+            mkdir /mnt/$x
+            ifuse /mnt/$x
+        elif [[ $option =~ $re ]] ; then
+            if ! [ $option -ge $i ]; then
+                mkdir /mnt/$x
+                ifuse --appid ${appid[$option]} /mnt/$x
+            fi
+        fi
     fi
 }
 
-alias lm='ls /mnt/'
+ios-umnt()
+{
+    cd
+    if [ -d /mnt/$1 ]; then
+        fusermount -u /mnt/$1
+    elif [ $1 = "-n" ]; then
+        shift 1
+        for x in $@
+        do
+            x="ios$x"
+            fusermount -u /mnt/$x
+        done
+    fi
+    rmdir /mnt/* &> /dev/null
+    cd - &> /dev/null
+}
 
 
+#-------------------------------------------------------------------------------
 # FTP
+#-------------------------------------------------------------------------------
+
 ftp-mnt()
 {
-    rmdir /ftp/* &> /dev/null
-    if [ $1 = "-c" -o $1 = "--custom-name" ]
-    then
+    if [ $1 = "-c" ]; then
         shift 1
         mkdir /ftp/$1
         curlftpfs $2 /ftp/$1
     else
-        x=0
+        i=0
         for x1 in $@
         do
-            flag=true
-            x2="server0"
-            while [ $flag = true ]
+            while [ true ]
             do
-                if [ -d /ftp/$x2 ]
-                then
-                    (( x++ ))
-                    x2="${x2::6}$x"
+                x2="server$i"
+                if [ -d /ftp/$x2 ]; then
+                    (( i++ ))
                 else
-                    flag=false
+                    break
                 fi
             done
             mkdir /ftp/$x2
@@ -125,11 +190,9 @@ ftp-mnt()
 ftp-umnt()
 {
     cd
-    if [ -d /ftp/$1 ]
-    then
+    if [ -d /ftp/$1 ]; then
         fusermount -u /ftp/$1
-    elif [ $1 = "-n" ]
-    then
+    elif [ $1 = "-n" ]; then
         shift 1
         for x in $@
         do
